// <auto-generated />
namespace LivrETS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addtablefairstep : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtablefairstep));
        
        string IMigrationMetadata.Id
        {
            get { return "201612311640193_add-table-fairstep"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
