// <auto-generated />
namespace LivrETS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_field_price_article : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_field_price_article));
        
        string IMigrationMetadata.Id
        {
            get { return "201609081843023_add_field_price_article"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
